apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-datasource
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: PostgreSQL
    type: postgres
    uid: postgres-datasource
    access: proxy
    url: postgres:5432
    database: $DATABASE_NAME
    user: $DATABASE_USER
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: $DATABASE_PASSWORD
