global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@eco-rindexer.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'

receivers:
  - name: 'default'
    webhook_configs:
      - url: '${ALERT_WEBHOOK_URL}'
        send_resolved: true
        title: 'Eco Rindexer Alert'
        text: |
          Alert: {{ .GroupLabels.alertname }}
          Status: {{ .Status }}
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']