global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # eRPC metrics - Primary RPC proxy
  - job_name: 'erpc'
    static_configs:
      - targets: ['erpc:4001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Rindexer health check (not metrics, just health status)
  # Note: rindexer does not expose Prometheus metrics
  # Monitor via database queries or GraphQL API instead

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # Grafana internal metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s