global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Rindexer metrics
  - job_name: 'rindexer'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL metrics (if pg_exporter is used)
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']
    scrape_interval: 30s

  # Node metrics (if node_exporter is used)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

  # Custom RPC health checks
  - job_name: 'rpc-health'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/health'
    scrape_interval: 60s